repos:
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3.13

  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile=black"]
        language_version: python3.13

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --extend-ignore=E203,W503
          - --config=pyproject.toml
        language_version: python3.13
        additional_dependencies:
          - flake8-bugbear>=24.8,<25.0
          - flake8-comprehensions>=3.14,<4.0
        exclude: '(^|/)(migrations|\.venv|venv)/'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args:
          - --show-traceback
          - --show-error-codes
          - --pretty
        language_version: python3.13
        additional_dependencies:
          - Django>=5.2,<5.3
          - django-bootstrap5>=25.1,<25.2
          - django-environ>=0.11,<0.12
          - django-filter>=25.1,<25.2
          - django-stubs>=5.0,<6.0
          - celery>=5.5,<5.6
          - redis>=6.4,<7.0
          - requests>=2.32,<3.0
          - types-requests>=2.32,<3.0